# Stage 1: Build
FROM node:20-alpine AS builder

# Cài đặt gói phụ trợ cho việc build (nếu cần)
RUN apk add --no-cache libc6-compat

# Tạo thư mục app
WORKDIR /app

# Copy file phụ thuộc
COPY package.json yarn.lock ./

# Cài đặt dependencies
RUN yarn install 

# Copy toàn bộ mã nguồn
COPY . .


# Port ứng dụng chạy
EXPOSE 8083

# Start app
CMD ["yarn", "dev"]
