export const PERMISSIONS = {
  REPORT: {
    VIEW: 'REPORT_VIEW',
  },
  STOCK_TRANSACTION: {
    CREATE: 'STOCK_TRANSACTION_CREATE',
    UPDATE: 'STOCK_TRANSACTION_UPDATE',
    CANCEL: 'STOCK_TRANSACTION_CANCEL',
    VIEW: 'STOCK_TRANSACTION_VIEW',
  },
  INVOICE: {
    CREATE: 'INVOICE_CREATE',
    CANCEL: 'INVOICE_CANCEL',
    VIEW: 'INVOICE_VIEW',
  },
  CUSTOMER: {
    CREATE: 'CUSTOMER_CREATE',
    UPDATE: 'CUSTOMER_UPDATE',
    DELETE: 'CUSTOMER_DELETE',
    VIEW: 'CUSTOMER_VIEW',
  },
  PRODUCT_LOT: {
    CREATE: 'PRODUCT_LOT_CREATE',
    UPDATE: 'PRODUCT_LOT_UPDATE',
    DELETE: 'PRODUCT_LOT_DELETE',
    VIEW: 'PRODUCT_LOT_VIEW',
  },
  USER: {
    CREATE: 'USER_CREATE',
    UPDATE: 'USER_UPDATE',
    DELETE: 'USER_DELETE',
    VIEW: 'USER_VIEW',
  },
  SUPPLIER: {
    CREATE: 'SUPPLIER_CREATE',
    UPDATE: 'SUPPLIER_UPDATE',
    DELETE: 'SUPPLIER_DELETE',
    VIEW: 'SUPPLIER_VIEW',
  },
  MANUFACTURER: {
    CREATE: 'MANUFACTURER_CREATE',
    UPDATE: 'MANUFACTURER_UPDATE',
    DELETE: 'MANUFACTURER_DELETE',
    VIEW: 'MANUFACTURER_VIEW',
  },
  CUSTOMER_GROUP: {
    CREATE: 'CUSTOMER_GROUP_CREATE',
    UPDATE: 'CUSTOMER_GROUP_UPDATE',
    DELETE: 'CUSTOMER_GROUP_DELETE',
    VIEW: 'CUSTOMER_GROUP_VIEW',
  },
  SUPPLIER_GROUP: {
    CREATE: 'SUPPLIER_GROUP_CREATE',
    UPDATE: 'SUPPLIER_GROUP_UPDATE',
    DELETE: 'SUPPLIER_GROUP_DELETE',
    VIEW: 'SUPPLIER_GROUP_VIEW',
  },
  ROLE: {
    CREATE: 'ROLE_CREATE',
    UPDATE: 'ROLE_UPDATE',
    DELETE: 'ROLE_DELETE',
    VIEW: 'ROLE_VIEW',
  },
  PRODUCT_GROUP: {
    CREATE: 'PRODUCT_GROUP_CREATE',
    UPDATE: 'PRODUCT_GROUP_UPDATE',
    DELETE: 'PRODUCT_GROUP_DELETE',
    VIEW: 'PRODUCT_GROUP_VIEW',
  },
  PAYMENT_METHOD: {
    UPSERT: 'PAYMENT_METHOD_UPSERT',
    VIEW: 'PAYMENT_METHOD_VIEW',
  },
  PRODUCT: {
    CREATE: 'PRODUCT_CREATE',
    UPDATE: 'PRODUCT_UPDATE',
    DELETE: 'PRODUCT_DELETE',
    VIEW: 'PRODUCT_VIEW',
  },
  STOCK_CARD: {
    VIEW: 'STOCK_CARD_VIEW',
  },
  PRODUCT_LOCATION: {
    CREATE: 'PRODUCT_LOCATION_CREATE',
    UPDATE: 'PRODUCT_LOCATION_UPDATE',
    DELETE: 'PRODUCT_LOCATION_DELETE',
    VIEW: 'PRODUCT_LOCATION_VIEW',
  },
  MEDICINE_ROUTE: {
    CREATE: 'MEDICINE_ROUTE_CREATE',
    UPDATE: 'MEDICINE_ROUTE_UPDATE',
    DELETE: 'MEDICINE_ROUTE_DELETE',
    VIEW: 'MEDICINE_ROUTE_VIEW',
  },
  VIEW: {
    MANAGER: 'MANAGER_VIEW',
    SALE: 'SALE_VIEW',
  },
};
